apiVersion: v1
kind: Service
metadata:
  name: themed-web-service
spec:
  type: NodePort
  selector:
    app: themed-web
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 30080
